version: '3.7'
services:
    nginx:
      image: nginx:latest
      ports:
      - target: 80
        published: 80        
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      depends_on:
      - client
      - server
    server:
      build:
        context: ./server
      ports:
      - target: 8080
        protocol: tcp
    client:
      build:
        context: ./client
      ports:
      - target: 3000
        protocol: tcp
      environment:
      - REACT_APP_SERVICE_HOST=${REACT_APP_SERVICE_HOST}
    mongo:
      image: mongo:latest
      ports:
      - target: 27017
        protocol: tcp      
    mongo-seed:
      image: fvilers/mongo-seed:1.0.0
      environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      volumes:
      - ./data:/data
      command:
      - "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/account.json --jsonArray"
